// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.timedesk.entity.ApplicationFeature;

privileged aspect ApplicationFeatureDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ApplicationFeatureDataOnDemand: @Component;
    
    private Random ApplicationFeatureDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ApplicationFeature> ApplicationFeatureDataOnDemand.data;
    
    public ApplicationFeature ApplicationFeatureDataOnDemand.getNewTransientApplicationFeature(int index) {
        org.timedesk.entity.ApplicationFeature obj = new org.timedesk.entity.ApplicationFeature();
        obj.setDescription(null);
        obj.setFeatureId("featureId_" + index);
        obj.setName("name_" + index);
        return obj;
    }
    
    public ApplicationFeature ApplicationFeatureDataOnDemand.getSpecificApplicationFeature(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ApplicationFeature obj = data.get(index);
        return ApplicationFeature.findApplicationFeature(obj.getId());
    }
    
    public ApplicationFeature ApplicationFeatureDataOnDemand.getRandomApplicationFeature() {
        init();
        ApplicationFeature obj = data.get(rnd.nextInt(data.size()));
        return ApplicationFeature.findApplicationFeature(obj.getId());
    }
    
    public boolean ApplicationFeatureDataOnDemand.modifyApplicationFeature(ApplicationFeature obj) {
        return false;
    }
    
    public void ApplicationFeatureDataOnDemand.init() {
        data = org.timedesk.entity.ApplicationFeature.findApplicationFeatureEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ApplicationFeature' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.ApplicationFeature>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.ApplicationFeature obj = getNewTransientApplicationFeature(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
