// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.ApplicationFeatureDataOnDemand;

privileged aspect ApplicationFeatureIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ApplicationFeatureIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ApplicationFeatureIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ApplicationFeatureIntegrationTest: @Transactional;
    
    @Autowired
    private ApplicationFeatureDataOnDemand ApplicationFeatureIntegrationTest.dod;
    
    @Test
    public void ApplicationFeatureIntegrationTest.testCountApplicationFeatures() {
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", dod.getRandomApplicationFeature());
        long count = org.timedesk.entity.ApplicationFeature.countApplicationFeatures();
        org.junit.Assert.assertTrue("Counter for 'ApplicationFeature' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ApplicationFeatureIntegrationTest.testFindApplicationFeature() {
        org.timedesk.entity.ApplicationFeature obj = dod.getRandomApplicationFeature();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to provide an identifier", id);
        obj = org.timedesk.entity.ApplicationFeature.findApplicationFeature(id);
        org.junit.Assert.assertNotNull("Find method for 'ApplicationFeature' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ApplicationFeature' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ApplicationFeatureIntegrationTest.testFindAllApplicationFeatures() {
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", dod.getRandomApplicationFeature());
        long count = org.timedesk.entity.ApplicationFeature.countApplicationFeatures();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ApplicationFeature', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.ApplicationFeature> result = org.timedesk.entity.ApplicationFeature.findAllApplicationFeatures();
        org.junit.Assert.assertNotNull("Find all method for 'ApplicationFeature' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ApplicationFeature' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ApplicationFeatureIntegrationTest.testFindApplicationFeatureEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", dod.getRandomApplicationFeature());
        long count = org.timedesk.entity.ApplicationFeature.countApplicationFeatures();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.ApplicationFeature> result = org.timedesk.entity.ApplicationFeature.findApplicationFeatureEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ApplicationFeature' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ApplicationFeature' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ApplicationFeatureIntegrationTest.testFlush() {
        org.timedesk.entity.ApplicationFeature obj = dod.getRandomApplicationFeature();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to provide an identifier", id);
        obj = org.timedesk.entity.ApplicationFeature.findApplicationFeature(id);
        org.junit.Assert.assertNotNull("Find method for 'ApplicationFeature' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApplicationFeature(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ApplicationFeature' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationFeatureIntegrationTest.testMerge() {
        org.timedesk.entity.ApplicationFeature obj = dod.getRandomApplicationFeature();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to provide an identifier", id);
        obj = org.timedesk.entity.ApplicationFeature.findApplicationFeature(id);
        boolean modified =  dod.modifyApplicationFeature(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.ApplicationFeature merged = (org.timedesk.entity.ApplicationFeature) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ApplicationFeature' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationFeatureIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", dod.getRandomApplicationFeature());
        org.timedesk.entity.ApplicationFeature obj = dod.getNewTransientApplicationFeature(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ApplicationFeature' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ApplicationFeature' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ApplicationFeatureIntegrationTest.testRemove() {
        org.timedesk.entity.ApplicationFeature obj = dod.getRandomApplicationFeature();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ApplicationFeature' failed to provide an identifier", id);
        obj = org.timedesk.entity.ApplicationFeature.findApplicationFeature(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ApplicationFeature' with identifier '" + id + "'", org.timedesk.entity.ApplicationFeature.findApplicationFeature(id));
    }
    
}
