// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.timedesk.entity.Company;

privileged aspect CompanyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CompanyDataOnDemand: @Component;
    
    private Random CompanyDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Company> CompanyDataOnDemand.data;
    
    public Company CompanyDataOnDemand.getNewTransientCompany(int index) {
        org.timedesk.entity.Company obj = new org.timedesk.entity.Company();
        obj.setCompanyId("companyId_" + index);
        obj.setName(null);
        return obj;
    }
    
    public Company CompanyDataOnDemand.getSpecificCompany(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Company obj = data.get(index);
        return Company.findCompany(obj.getId());
    }
    
    public Company CompanyDataOnDemand.getRandomCompany() {
        init();
        Company obj = data.get(rnd.nextInt(data.size()));
        return Company.findCompany(obj.getId());
    }
    
    public boolean CompanyDataOnDemand.modifyCompany(Company obj) {
        return false;
    }
    
    public void CompanyDataOnDemand.init() {
        data = org.timedesk.entity.Company.findCompanyEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Company' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.Company>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.Company obj = getNewTransientCompany(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
