// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.CompanySiteDataOnDemand;
import org.timedesk.entity.Employee;

privileged aspect EmployeeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployeeDataOnDemand: @Component;
    
    private Random EmployeeDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Employee> EmployeeDataOnDemand.data;
    
    @Autowired
    private CompanySiteDataOnDemand EmployeeDataOnDemand.companySiteDataOnDemand;
    
    public Employee EmployeeDataOnDemand.getNewTransientEmployee(int index) {
        org.timedesk.entity.Employee obj = new org.timedesk.entity.Employee();
        obj.setAddress(null);
        obj.setCity(null);
        obj.setCompanySite(companySiteDataOnDemand.getRandomCompanySite());
        obj.setCountry(null);
        obj.setEmail(null);
        obj.setEmployeeId(null);
        obj.setFirstName("firstName_" + index);
        obj.setLastName("lastName_" + index);
        obj.setMaxAllocation(new Integer(index));
        obj.setOfficeExtension(null);
        obj.setPhoneMobile(null);
        obj.setPhoneResidence(null);
        obj.setPostCode(null);
        obj.setUser(null);
        return obj;
    }
    
    public Employee EmployeeDataOnDemand.getSpecificEmployee(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Employee obj = data.get(index);
        return Employee.findEmployee(obj.getId());
    }
    
    public Employee EmployeeDataOnDemand.getRandomEmployee() {
        init();
        Employee obj = data.get(rnd.nextInt(data.size()));
        return Employee.findEmployee(obj.getId());
    }
    
    public boolean EmployeeDataOnDemand.modifyEmployee(Employee obj) {
        return false;
    }
    
    public void EmployeeDataOnDemand.init() {
        data = org.timedesk.entity.Employee.findEmployeeEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Employee' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.Employee>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.Employee obj = getNewTransientEmployee(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
