// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.EmployeeRoleDataOnDemand;

privileged aspect EmployeeRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeeRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeeRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EmployeeRoleIntegrationTest: @Transactional;
    
    @Autowired
    private EmployeeRoleDataOnDemand EmployeeRoleIntegrationTest.dod;
    
    @Test
    public void EmployeeRoleIntegrationTest.testCountEmployeeRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", dod.getRandomEmployeeRole());
        long count = org.timedesk.entity.EmployeeRole.countEmployeeRoles();
        org.junit.Assert.assertTrue("Counter for 'EmployeeRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeeRoleIntegrationTest.testFindEmployeeRole() {
        org.timedesk.entity.EmployeeRole obj = dod.getRandomEmployeeRole();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeRole.findEmployeeRole(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeRole' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'EmployeeRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeeRoleIntegrationTest.testFindAllEmployeeRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", dod.getRandomEmployeeRole());
        long count = org.timedesk.entity.EmployeeRole.countEmployeeRoles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'EmployeeRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.EmployeeRole> result = org.timedesk.entity.EmployeeRole.findAllEmployeeRoles();
        org.junit.Assert.assertNotNull("Find all method for 'EmployeeRole' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'EmployeeRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeeRoleIntegrationTest.testFindEmployeeRoleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", dod.getRandomEmployeeRole());
        long count = org.timedesk.entity.EmployeeRole.countEmployeeRoles();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.EmployeeRole> result = org.timedesk.entity.EmployeeRole.findEmployeeRoleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'EmployeeRole' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'EmployeeRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeeRoleIntegrationTest.testFlush() {
        org.timedesk.entity.EmployeeRole obj = dod.getRandomEmployeeRole();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeRole.findEmployeeRole(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployeeRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'EmployeeRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeRoleIntegrationTest.testMerge() {
        org.timedesk.entity.EmployeeRole obj = dod.getRandomEmployeeRole();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeRole.findEmployeeRole(id);
        boolean modified =  dod.modifyEmployeeRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.EmployeeRole merged = (org.timedesk.entity.EmployeeRole) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'EmployeeRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeRoleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", dod.getRandomEmployeeRole());
        org.timedesk.entity.EmployeeRole obj = dod.getNewTransientEmployeeRole(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'EmployeeRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'EmployeeRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeeRoleIntegrationTest.testRemove() {
        org.timedesk.entity.EmployeeRole obj = dod.getRandomEmployeeRole();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeRole.findEmployeeRole(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'EmployeeRole' with identifier '" + id + "'", org.timedesk.entity.EmployeeRole.findEmployeeRole(id));
    }
    
}
