// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.EmployeeLeaveDataOnDemand;

privileged aspect EmployeeLeaveIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeeLeaveIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeeLeaveIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EmployeeLeaveIntegrationTest: @Transactional;
    
    @Autowired
    private EmployeeLeaveDataOnDemand EmployeeLeaveIntegrationTest.dod;
    
    @Test
    public void EmployeeLeaveIntegrationTest.testCountEmployeeLeaves() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", dod.getRandomEmployeeLeave());
        long count = org.timedesk.entity.EmployeeLeave.countEmployeeLeaves();
        org.junit.Assert.assertTrue("Counter for 'EmployeeLeave' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeeLeaveIntegrationTest.testFindEmployeeLeave() {
        org.timedesk.entity.EmployeeLeave obj = dod.getRandomEmployeeLeave();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeLeave.findEmployeeLeave(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeLeave' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'EmployeeLeave' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeeLeaveIntegrationTest.testFindAllEmployeeLeaves() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", dod.getRandomEmployeeLeave());
        long count = org.timedesk.entity.EmployeeLeave.countEmployeeLeaves();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'EmployeeLeave', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.EmployeeLeave> result = org.timedesk.entity.EmployeeLeave.findAllEmployeeLeaves();
        org.junit.Assert.assertNotNull("Find all method for 'EmployeeLeave' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'EmployeeLeave' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeeLeaveIntegrationTest.testFindEmployeeLeaveEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", dod.getRandomEmployeeLeave());
        long count = org.timedesk.entity.EmployeeLeave.countEmployeeLeaves();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.EmployeeLeave> result = org.timedesk.entity.EmployeeLeave.findEmployeeLeaveEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'EmployeeLeave' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'EmployeeLeave' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeeLeaveIntegrationTest.testFlush() {
        org.timedesk.entity.EmployeeLeave obj = dod.getRandomEmployeeLeave();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeLeave.findEmployeeLeave(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeLeave' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployeeLeave(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'EmployeeLeave' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeLeaveIntegrationTest.testMerge() {
        org.timedesk.entity.EmployeeLeave obj = dod.getRandomEmployeeLeave();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeLeave.findEmployeeLeave(id);
        boolean modified =  dod.modifyEmployeeLeave(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.EmployeeLeave merged = (org.timedesk.entity.EmployeeLeave) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'EmployeeLeave' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeLeaveIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", dod.getRandomEmployeeLeave());
        org.timedesk.entity.EmployeeLeave obj = dod.getNewTransientEmployeeLeave(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'EmployeeLeave' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'EmployeeLeave' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeeLeaveIntegrationTest.testRemove() {
        org.timedesk.entity.EmployeeLeave obj = dod.getRandomEmployeeLeave();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeLeave' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeLeave.findEmployeeLeave(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'EmployeeLeave' with identifier '" + id + "'", org.timedesk.entity.EmployeeLeave.findEmployeeLeave(id));
    }
    
}
