// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.timedesk.entity.EmployeeAllocation;

privileged aspect EmployeeAllocationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployeeAllocationDataOnDemand: @Component;
    
    private Random EmployeeAllocationDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<EmployeeAllocation> EmployeeAllocationDataOnDemand.data;
    
    public EmployeeAllocation EmployeeAllocationDataOnDemand.getNewTransientEmployeeAllocation(int index) {
        org.timedesk.entity.EmployeeAllocation obj = new org.timedesk.entity.EmployeeAllocation();
        obj.setAllocation(new Integer(index));
        obj.setEmpId(new Integer(index).longValue());
        obj.setEmployeeId("employeeId_" + index);
        obj.setEndDate(new java.util.Date());
        obj.setPhmId(new Integer(index).longValue());
        obj.setStartDate(new java.util.Date());
        return obj;
    }
    
    public EmployeeAllocation EmployeeAllocationDataOnDemand.getSpecificEmployeeAllocation(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        EmployeeAllocation obj = data.get(index);
        return EmployeeAllocation.findEmployeeAllocation(obj.getId());
    }
    
    public EmployeeAllocation EmployeeAllocationDataOnDemand.getRandomEmployeeAllocation() {
        init();
        EmployeeAllocation obj = data.get(rnd.nextInt(data.size()));
        return EmployeeAllocation.findEmployeeAllocation(obj.getId());
    }
    
    public boolean EmployeeAllocationDataOnDemand.modifyEmployeeAllocation(EmployeeAllocation obj) {
        return false;
    }
    
    public void EmployeeAllocationDataOnDemand.init() {
        data = org.timedesk.entity.EmployeeAllocation.findEmployeeAllocationEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'EmployeeAllocation' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.EmployeeAllocation>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.EmployeeAllocation obj = getNewTransientEmployeeAllocation(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
