// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.EmployeeDataOnDemand;
import org.timedesk.entity.EmployeeVisa;

privileged aspect EmployeeVisaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployeeVisaDataOnDemand: @Component;
    
    private Random EmployeeVisaDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<EmployeeVisa> EmployeeVisaDataOnDemand.data;
    
    @Autowired
    private EmployeeDataOnDemand EmployeeVisaDataOnDemand.employeeDataOnDemand;
    
    public EmployeeVisa EmployeeVisaDataOnDemand.getNewTransientEmployeeVisa(int index) {
        org.timedesk.entity.EmployeeVisa obj = new org.timedesk.entity.EmployeeVisa();
        obj.setCountry(org.timedesk.entity.CountryEnum.class.getEnumConstants()[0]);
        obj.setEmployee(employeeDataOnDemand.getRandomEmployee());
        obj.setValidFrom(new java.util.Date());
        obj.setValidTo(new java.util.Date());
        obj.setVisaId("visaId_" + index);
        return obj;
    }
    
    public EmployeeVisa EmployeeVisaDataOnDemand.getSpecificEmployeeVisa(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        EmployeeVisa obj = data.get(index);
        return EmployeeVisa.findEmployeeVisa(obj.getId());
    }
    
    public EmployeeVisa EmployeeVisaDataOnDemand.getRandomEmployeeVisa() {
        init();
        EmployeeVisa obj = data.get(rnd.nextInt(data.size()));
        return EmployeeVisa.findEmployeeVisa(obj.getId());
    }
    
    public boolean EmployeeVisaDataOnDemand.modifyEmployeeVisa(EmployeeVisa obj) {
        return false;
    }
    
    public void EmployeeVisaDataOnDemand.init() {
        data = org.timedesk.entity.EmployeeVisa.findEmployeeVisaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'EmployeeVisa' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.EmployeeVisa>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.EmployeeVisa obj = getNewTransientEmployeeVisa(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
