// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.EmployeeDataOnDemand;
import org.timedesk.entity.EmployeeLeave;

privileged aspect EmployeeLeaveDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployeeLeaveDataOnDemand: @Component;
    
    private Random EmployeeLeaveDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<EmployeeLeave> EmployeeLeaveDataOnDemand.data;
    
    @Autowired
    private EmployeeDataOnDemand EmployeeLeaveDataOnDemand.employeeDataOnDemand;
    
    public EmployeeLeave EmployeeLeaveDataOnDemand.getNewTransientEmployeeLeave(int index) {
        org.timedesk.entity.EmployeeLeave obj = new org.timedesk.entity.EmployeeLeave();
        obj.setEmployee(employeeDataOnDemand.getRandomEmployee());
        obj.setFromTime(new java.util.Date());
        obj.setToTime(new java.util.Date());
        return obj;
    }
    
    public EmployeeLeave EmployeeLeaveDataOnDemand.getSpecificEmployeeLeave(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        EmployeeLeave obj = data.get(index);
        return EmployeeLeave.findEmployeeLeave(obj.getId());
    }
    
    public EmployeeLeave EmployeeLeaveDataOnDemand.getRandomEmployeeLeave() {
        init();
        EmployeeLeave obj = data.get(rnd.nextInt(data.size()));
        return EmployeeLeave.findEmployeeLeave(obj.getId());
    }
    
    public boolean EmployeeLeaveDataOnDemand.modifyEmployeeLeave(EmployeeLeave obj) {
        return false;
    }
    
    public void EmployeeLeaveDataOnDemand.init() {
        data = org.timedesk.entity.EmployeeLeave.findEmployeeLeaveEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'EmployeeLeave' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.EmployeeLeave>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.EmployeeLeave obj = getNewTransientEmployeeLeave(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
