// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.ProjectMemberRoleDataOnDemand;

privileged aspect ProjectMemberRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjectMemberRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjectMemberRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProjectMemberRoleIntegrationTest: @Transactional;
    
    @Autowired
    private ProjectMemberRoleDataOnDemand ProjectMemberRoleIntegrationTest.dod;
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testCountProjectMemberRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", dod.getRandomProjectMemberRole());
        long count = org.timedesk.entity.ProjectMemberRole.countProjectMemberRoles();
        org.junit.Assert.assertTrue("Counter for 'ProjectMemberRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testFindProjectMemberRole() {
        org.timedesk.entity.ProjectMemberRole obj = dod.getRandomProjectMemberRole();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberRole.findProjectMemberRole(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectMemberRole' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProjectMemberRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testFindAllProjectMemberRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", dod.getRandomProjectMemberRole());
        long count = org.timedesk.entity.ProjectMemberRole.countProjectMemberRoles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProjectMemberRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.ProjectMemberRole> result = org.timedesk.entity.ProjectMemberRole.findAllProjectMemberRoles();
        org.junit.Assert.assertNotNull("Find all method for 'ProjectMemberRole' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProjectMemberRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testFindProjectMemberRoleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", dod.getRandomProjectMemberRole());
        long count = org.timedesk.entity.ProjectMemberRole.countProjectMemberRoles();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.ProjectMemberRole> result = org.timedesk.entity.ProjectMemberRole.findProjectMemberRoleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProjectMemberRole' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProjectMemberRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testFlush() {
        org.timedesk.entity.ProjectMemberRole obj = dod.getRandomProjectMemberRole();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberRole.findProjectMemberRole(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectMemberRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjectMemberRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProjectMemberRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testMerge() {
        org.timedesk.entity.ProjectMemberRole obj = dod.getRandomProjectMemberRole();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberRole.findProjectMemberRole(id);
        boolean modified =  dod.modifyProjectMemberRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.ProjectMemberRole merged = (org.timedesk.entity.ProjectMemberRole) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProjectMemberRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", dod.getRandomProjectMemberRole());
        org.timedesk.entity.ProjectMemberRole obj = dod.getNewTransientProjectMemberRole(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProjectMemberRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProjectMemberRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjectMemberRoleIntegrationTest.testRemove() {
        org.timedesk.entity.ProjectMemberRole obj = dod.getRandomProjectMemberRole();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberRole.findProjectMemberRole(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProjectMemberRole' with identifier '" + id + "'", org.timedesk.entity.ProjectMemberRole.findProjectMemberRole(id));
    }
    
}
