// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.EmployeeDataOnDemand;
import org.timedesk.entity.ProjectDataOnDemand;
import org.timedesk.entity.ProjectMember;

privileged aspect ProjectMemberDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectMemberDataOnDemand: @Component;
    
    private Random ProjectMemberDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ProjectMember> ProjectMemberDataOnDemand.data;
    
    @Autowired
    private EmployeeDataOnDemand ProjectMemberDataOnDemand.employeeDataOnDemand;
    
    @Autowired
    private ProjectDataOnDemand ProjectMemberDataOnDemand.projectDataOnDemand;
    
    public ProjectMember ProjectMemberDataOnDemand.getNewTransientProjectMember(int index) {
        org.timedesk.entity.ProjectMember obj = new org.timedesk.entity.ProjectMember();
        obj.setEmployee(employeeDataOnDemand.getSpecificEmployee(index));
        obj.setMemberId(null);
        obj.setProject(projectDataOnDemand.getRandomProject());
        return obj;
    }
    
    public ProjectMember ProjectMemberDataOnDemand.getSpecificProjectMember(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ProjectMember obj = data.get(index);
        return ProjectMember.findProjectMember(obj.getId());
    }
    
    public ProjectMember ProjectMemberDataOnDemand.getRandomProjectMember() {
        init();
        ProjectMember obj = data.get(rnd.nextInt(data.size()));
        return ProjectMember.findProjectMember(obj.getId());
    }
    
    public boolean ProjectMemberDataOnDemand.modifyProjectMember(ProjectMember obj) {
        return false;
    }
    
    public void ProjectMemberDataOnDemand.init() {
        data = org.timedesk.entity.ProjectMember.findProjectMemberEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ProjectMember' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.ProjectMember>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.ProjectMember obj = getNewTransientProjectMember(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
