// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.CompanyDataOnDemand;
import org.timedesk.entity.Project;

privileged aspect ProjectDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectDataOnDemand: @Component;
    
    private Random ProjectDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Project> ProjectDataOnDemand.data;
    
    @Autowired
    private CompanyDataOnDemand ProjectDataOnDemand.companyDataOnDemand;
    
    public Project ProjectDataOnDemand.getNewTransientProject(int index) {
        org.timedesk.entity.Project obj = new org.timedesk.entity.Project();
        obj.setCompany(companyDataOnDemand.getRandomCompany());
        obj.setDescription(null);
        obj.setEndDate(new java.util.Date());
        obj.setName("name_" + index);
        obj.setProjectId("projectId_" + index);
        obj.setStartDate(new java.util.Date());
        return obj;
    }
    
    public Project ProjectDataOnDemand.getSpecificProject(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Project obj = data.get(index);
        return Project.findProject(obj.getId());
    }
    
    public Project ProjectDataOnDemand.getRandomProject() {
        init();
        Project obj = data.get(rnd.nextInt(data.size()));
        return Project.findProject(obj.getId());
    }
    
    public boolean ProjectDataOnDemand.modifyProject(Project obj) {
        return false;
    }
    
    public void ProjectDataOnDemand.init() {
        data = org.timedesk.entity.Project.findProjectEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Project' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.Project>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.Project obj = getNewTransientProject(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
