// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.ProjectPhaseDataOnDemand;

privileged aspect ProjectPhaseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjectPhaseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjectPhaseIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProjectPhaseIntegrationTest: @Transactional;
    
    @Autowired
    private ProjectPhaseDataOnDemand ProjectPhaseIntegrationTest.dod;
    
    @Test
    public void ProjectPhaseIntegrationTest.testCountProjectPhases() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", dod.getRandomProjectPhase());
        long count = org.timedesk.entity.ProjectPhase.countProjectPhases();
        org.junit.Assert.assertTrue("Counter for 'ProjectPhase' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjectPhaseIntegrationTest.testFindProjectPhase() {
        org.timedesk.entity.ProjectPhase obj = dod.getRandomProjectPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhase.findProjectPhase(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectPhase' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProjectPhase' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjectPhaseIntegrationTest.testFindAllProjectPhases() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", dod.getRandomProjectPhase());
        long count = org.timedesk.entity.ProjectPhase.countProjectPhases();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProjectPhase', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.ProjectPhase> result = org.timedesk.entity.ProjectPhase.findAllProjectPhases();
        org.junit.Assert.assertNotNull("Find all method for 'ProjectPhase' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProjectPhase' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjectPhaseIntegrationTest.testFindProjectPhaseEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", dod.getRandomProjectPhase());
        long count = org.timedesk.entity.ProjectPhase.countProjectPhases();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.ProjectPhase> result = org.timedesk.entity.ProjectPhase.findProjectPhaseEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProjectPhase' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProjectPhase' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjectPhaseIntegrationTest.testFlush() {
        org.timedesk.entity.ProjectPhase obj = dod.getRandomProjectPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhase.findProjectPhase(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectPhase' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjectPhase(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProjectPhase' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectPhaseIntegrationTest.testMerge() {
        org.timedesk.entity.ProjectPhase obj = dod.getRandomProjectPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhase.findProjectPhase(id);
        boolean modified =  dod.modifyProjectPhase(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.ProjectPhase merged = (org.timedesk.entity.ProjectPhase) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProjectPhase' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectPhaseIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", dod.getRandomProjectPhase());
        org.timedesk.entity.ProjectPhase obj = dod.getNewTransientProjectPhase(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProjectPhase' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProjectPhase' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjectPhaseIntegrationTest.testRemove() {
        org.timedesk.entity.ProjectPhase obj = dod.getRandomProjectPhase();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhase' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhase.findProjectPhase(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProjectPhase' with identifier '" + id + "'", org.timedesk.entity.ProjectPhase.findProjectPhase(id));
    }
    
}
