// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.ProjectMemberDataOnDemand;

privileged aspect ProjectMemberIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjectMemberIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjectMemberIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProjectMemberIntegrationTest: @Transactional;
    
    @Autowired
    private ProjectMemberDataOnDemand ProjectMemberIntegrationTest.dod;
    
    @Test
    public void ProjectMemberIntegrationTest.testCountProjectMembers() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", dod.getRandomProjectMember());
        long count = org.timedesk.entity.ProjectMember.countProjectMembers();
        org.junit.Assert.assertTrue("Counter for 'ProjectMember' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjectMemberIntegrationTest.testFindProjectMember() {
        org.timedesk.entity.ProjectMember obj = dod.getRandomProjectMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMember.findProjectMember(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectMember' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProjectMember' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjectMemberIntegrationTest.testFindAllProjectMembers() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", dod.getRandomProjectMember());
        long count = org.timedesk.entity.ProjectMember.countProjectMembers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProjectMember', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.ProjectMember> result = org.timedesk.entity.ProjectMember.findAllProjectMembers();
        org.junit.Assert.assertNotNull("Find all method for 'ProjectMember' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProjectMember' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjectMemberIntegrationTest.testFindProjectMemberEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", dod.getRandomProjectMember());
        long count = org.timedesk.entity.ProjectMember.countProjectMembers();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.ProjectMember> result = org.timedesk.entity.ProjectMember.findProjectMemberEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProjectMember' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProjectMember' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjectMemberIntegrationTest.testFlush() {
        org.timedesk.entity.ProjectMember obj = dod.getRandomProjectMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMember.findProjectMember(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectMember' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjectMember(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProjectMember' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectMemberIntegrationTest.testMerge() {
        org.timedesk.entity.ProjectMember obj = dod.getRandomProjectMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMember.findProjectMember(id);
        boolean modified =  dod.modifyProjectMember(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.ProjectMember merged = (org.timedesk.entity.ProjectMember) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProjectMember' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectMemberIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", dod.getRandomProjectMember());
        org.timedesk.entity.ProjectMember obj = dod.getNewTransientProjectMember(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProjectMember' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProjectMember' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjectMemberIntegrationTest.testRemove() {
        org.timedesk.entity.ProjectMember obj = dod.getRandomProjectMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMember.findProjectMember(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProjectMember' with identifier '" + id + "'", org.timedesk.entity.ProjectMember.findProjectMember(id));
    }
    
}
