// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.SecurityRoleDataOnDemand;

privileged aspect SecurityRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SecurityRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SecurityRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SecurityRoleIntegrationTest: @Transactional;
    
    @Autowired
    private SecurityRoleDataOnDemand SecurityRoleIntegrationTest.dod;
    
    @Test
    public void SecurityRoleIntegrationTest.testCountSecurityRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", dod.getRandomSecurityRole());
        long count = org.timedesk.entity.SecurityRole.countSecurityRoles();
        org.junit.Assert.assertTrue("Counter for 'SecurityRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SecurityRoleIntegrationTest.testFindSecurityRole() {
        org.timedesk.entity.SecurityRole obj = dod.getRandomSecurityRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.SecurityRole.findSecurityRole(id);
        org.junit.Assert.assertNotNull("Find method for 'SecurityRole' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'SecurityRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SecurityRoleIntegrationTest.testFindAllSecurityRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", dod.getRandomSecurityRole());
        long count = org.timedesk.entity.SecurityRole.countSecurityRoles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'SecurityRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.SecurityRole> result = org.timedesk.entity.SecurityRole.findAllSecurityRoles();
        org.junit.Assert.assertNotNull("Find all method for 'SecurityRole' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'SecurityRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SecurityRoleIntegrationTest.testFindSecurityRoleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", dod.getRandomSecurityRole());
        long count = org.timedesk.entity.SecurityRole.countSecurityRoles();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.SecurityRole> result = org.timedesk.entity.SecurityRole.findSecurityRoleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'SecurityRole' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'SecurityRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SecurityRoleIntegrationTest.testFlush() {
        org.timedesk.entity.SecurityRole obj = dod.getRandomSecurityRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.SecurityRole.findSecurityRole(id);
        org.junit.Assert.assertNotNull("Find method for 'SecurityRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySecurityRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'SecurityRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SecurityRoleIntegrationTest.testMerge() {
        org.timedesk.entity.SecurityRole obj = dod.getRandomSecurityRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.SecurityRole.findSecurityRole(id);
        boolean modified =  dod.modifySecurityRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.SecurityRole merged = (org.timedesk.entity.SecurityRole) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'SecurityRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SecurityRoleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", dod.getRandomSecurityRole());
        org.timedesk.entity.SecurityRole obj = dod.getNewTransientSecurityRole(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'SecurityRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'SecurityRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SecurityRoleIntegrationTest.testRemove() {
        org.timedesk.entity.SecurityRole obj = dod.getRandomSecurityRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SecurityRole' failed to provide an identifier", id);
        obj = org.timedesk.entity.SecurityRole.findSecurityRole(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'SecurityRole' with identifier '" + id + "'", org.timedesk.entity.SecurityRole.findSecurityRole(id));
    }
    
}
