// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.timedesk.entity.Skill;

privileged aspect SkillDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SkillDataOnDemand: @Component;
    
    private Random SkillDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Skill> SkillDataOnDemand.data;
    
    public Skill SkillDataOnDemand.getNewTransientSkill(int index) {
        org.timedesk.entity.Skill obj = new org.timedesk.entity.Skill();
        obj.setDescription("description_" + index);
        obj.setSkillId("skillId_" + index);
        return obj;
    }
    
    public Skill SkillDataOnDemand.getSpecificSkill(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Skill obj = data.get(index);
        return Skill.findSkill(obj.getId());
    }
    
    public Skill SkillDataOnDemand.getRandomSkill() {
        init();
        Skill obj = data.get(rnd.nextInt(data.size()));
        return Skill.findSkill(obj.getId());
    }
    
    public boolean SkillDataOnDemand.modifySkill(Skill obj) {
        return false;
    }
    
    public void SkillDataOnDemand.init() {
        data = org.timedesk.entity.Skill.findSkillEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Skill' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.Skill>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.Skill obj = getNewTransientSkill(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
