// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.CompanyDataOnDemand;
import org.timedesk.entity.CompanySite;

privileged aspect CompanySiteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CompanySiteDataOnDemand: @Component;
    
    private Random CompanySiteDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<CompanySite> CompanySiteDataOnDemand.data;
    
    @Autowired
    private CompanyDataOnDemand CompanySiteDataOnDemand.companyDataOnDemand;
    
    public CompanySite CompanySiteDataOnDemand.getNewTransientCompanySite(int index) {
        org.timedesk.entity.CompanySite obj = new org.timedesk.entity.CompanySite();
        obj.setCity(null);
        obj.setCompany(companyDataOnDemand.getRandomCompany());
        obj.setCountry(null);
        obj.setLocation(null);
        obj.setSiteId("siteId_" + index);
        return obj;
    }
    
    public CompanySite CompanySiteDataOnDemand.getSpecificCompanySite(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        CompanySite obj = data.get(index);
        return CompanySite.findCompanySite(obj.getId());
    }
    
    public CompanySite CompanySiteDataOnDemand.getRandomCompanySite() {
        init();
        CompanySite obj = data.get(rnd.nextInt(data.size()));
        return CompanySite.findCompanySite(obj.getId());
    }
    
    public boolean CompanySiteDataOnDemand.modifyCompanySite(CompanySite obj) {
        return false;
    }
    
    public void CompanySiteDataOnDemand.init() {
        data = org.timedesk.entity.CompanySite.findCompanySiteEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'CompanySite' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.CompanySite>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.CompanySite obj = getNewTransientCompanySite(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
