// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.CompanySiteDataOnDemand;

privileged aspect CompanySiteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CompanySiteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CompanySiteIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CompanySiteIntegrationTest: @Transactional;
    
    @Autowired
    private CompanySiteDataOnDemand CompanySiteIntegrationTest.dod;
    
    @Test
    public void CompanySiteIntegrationTest.testCountCompanySites() {
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", dod.getRandomCompanySite());
        long count = org.timedesk.entity.CompanySite.countCompanySites();
        org.junit.Assert.assertTrue("Counter for 'CompanySite' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CompanySiteIntegrationTest.testFindCompanySite() {
        org.timedesk.entity.CompanySite obj = dod.getRandomCompanySite();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to provide an identifier", id);
        obj = org.timedesk.entity.CompanySite.findCompanySite(id);
        org.junit.Assert.assertNotNull("Find method for 'CompanySite' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CompanySite' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CompanySiteIntegrationTest.testFindAllCompanySites() {
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", dod.getRandomCompanySite());
        long count = org.timedesk.entity.CompanySite.countCompanySites();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CompanySite', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.CompanySite> result = org.timedesk.entity.CompanySite.findAllCompanySites();
        org.junit.Assert.assertNotNull("Find all method for 'CompanySite' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CompanySite' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CompanySiteIntegrationTest.testFindCompanySiteEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", dod.getRandomCompanySite());
        long count = org.timedesk.entity.CompanySite.countCompanySites();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.CompanySite> result = org.timedesk.entity.CompanySite.findCompanySiteEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CompanySite' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CompanySite' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CompanySiteIntegrationTest.testFlush() {
        org.timedesk.entity.CompanySite obj = dod.getRandomCompanySite();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to provide an identifier", id);
        obj = org.timedesk.entity.CompanySite.findCompanySite(id);
        org.junit.Assert.assertNotNull("Find method for 'CompanySite' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCompanySite(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CompanySite' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompanySiteIntegrationTest.testMerge() {
        org.timedesk.entity.CompanySite obj = dod.getRandomCompanySite();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to provide an identifier", id);
        obj = org.timedesk.entity.CompanySite.findCompanySite(id);
        boolean modified =  dod.modifyCompanySite(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.CompanySite merged = (org.timedesk.entity.CompanySite) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'CompanySite' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompanySiteIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", dod.getRandomCompanySite());
        org.timedesk.entity.CompanySite obj = dod.getNewTransientCompanySite(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CompanySite' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CompanySite' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CompanySiteIntegrationTest.testRemove() {
        org.timedesk.entity.CompanySite obj = dod.getRandomCompanySite();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CompanySite' failed to provide an identifier", id);
        obj = org.timedesk.entity.CompanySite.findCompanySite(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CompanySite' with identifier '" + id + "'", org.timedesk.entity.CompanySite.findCompanySite(id));
    }
    
}
