// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.timedesk.entity.EmployeeRole;

privileged aspect EmployeeRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployeeRoleDataOnDemand: @Component;
    
    private Random EmployeeRoleDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<EmployeeRole> EmployeeRoleDataOnDemand.data;
    
    public EmployeeRole EmployeeRoleDataOnDemand.getNewTransientEmployeeRole(int index) {
        org.timedesk.entity.EmployeeRole obj = new org.timedesk.entity.EmployeeRole();
        obj.setName("name_" + index);
        obj.setRoleId("roleId_" + index);
        return obj;
    }
    
    public EmployeeRole EmployeeRoleDataOnDemand.getSpecificEmployeeRole(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        EmployeeRole obj = data.get(index);
        return EmployeeRole.findEmployeeRole(obj.getId());
    }
    
    public EmployeeRole EmployeeRoleDataOnDemand.getRandomEmployeeRole() {
        init();
        EmployeeRole obj = data.get(rnd.nextInt(data.size()));
        return EmployeeRole.findEmployeeRole(obj.getId());
    }
    
    public boolean EmployeeRoleDataOnDemand.modifyEmployeeRole(EmployeeRole obj) {
        return false;
    }
    
    public void EmployeeRoleDataOnDemand.init() {
        data = org.timedesk.entity.EmployeeRole.findEmployeeRoleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'EmployeeRole' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.EmployeeRole>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.EmployeeRole obj = getNewTransientEmployeeRole(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
