// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.EmployeeDataOnDemand;

privileged aspect EmployeeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EmployeeIntegrationTest: @Transactional;
    
    @Autowired
    private EmployeeDataOnDemand EmployeeIntegrationTest.dod;
    
    @Test
    public void EmployeeIntegrationTest.testCountEmployees() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", dod.getRandomEmployee());
        long count = org.timedesk.entity.Employee.countEmployees();
        org.junit.Assert.assertTrue("Counter for 'Employee' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeeIntegrationTest.testFindEmployee() {
        org.timedesk.entity.Employee obj = dod.getRandomEmployee();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to provide an identifier", id);
        obj = org.timedesk.entity.Employee.findEmployee(id);
        org.junit.Assert.assertNotNull("Find method for 'Employee' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Employee' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeeIntegrationTest.testFindAllEmployees() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", dod.getRandomEmployee());
        long count = org.timedesk.entity.Employee.countEmployees();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Employee', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.Employee> result = org.timedesk.entity.Employee.findAllEmployees();
        org.junit.Assert.assertNotNull("Find all method for 'Employee' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Employee' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeeIntegrationTest.testFindEmployeeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", dod.getRandomEmployee());
        long count = org.timedesk.entity.Employee.countEmployees();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.Employee> result = org.timedesk.entity.Employee.findEmployeeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Employee' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Employee' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeeIntegrationTest.testFlush() {
        org.timedesk.entity.Employee obj = dod.getRandomEmployee();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to provide an identifier", id);
        obj = org.timedesk.entity.Employee.findEmployee(id);
        org.junit.Assert.assertNotNull("Find method for 'Employee' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployee(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Employee' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeIntegrationTest.testMerge() {
        org.timedesk.entity.Employee obj = dod.getRandomEmployee();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to provide an identifier", id);
        obj = org.timedesk.entity.Employee.findEmployee(id);
        boolean modified =  dod.modifyEmployee(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.Employee merged = (org.timedesk.entity.Employee) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Employee' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", dod.getRandomEmployee());
        org.timedesk.entity.Employee obj = dod.getNewTransientEmployee(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Employee' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Employee' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeeIntegrationTest.testRemove() {
        org.timedesk.entity.Employee obj = dod.getRandomEmployee();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employee' failed to provide an identifier", id);
        obj = org.timedesk.entity.Employee.findEmployee(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Employee' with identifier '" + id + "'", org.timedesk.entity.Employee.findEmployee(id));
    }
    
}
