// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.EmployeeVisaDataOnDemand;

privileged aspect EmployeeVisaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeeVisaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeeVisaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EmployeeVisaIntegrationTest: @Transactional;
    
    @Autowired
    private EmployeeVisaDataOnDemand EmployeeVisaIntegrationTest.dod;
    
    @Test
    public void EmployeeVisaIntegrationTest.testCountEmployeeVisas() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", dod.getRandomEmployeeVisa());
        long count = org.timedesk.entity.EmployeeVisa.countEmployeeVisas();
        org.junit.Assert.assertTrue("Counter for 'EmployeeVisa' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeeVisaIntegrationTest.testFindEmployeeVisa() {
        org.timedesk.entity.EmployeeVisa obj = dod.getRandomEmployeeVisa();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeVisa.findEmployeeVisa(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeVisa' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'EmployeeVisa' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeeVisaIntegrationTest.testFindAllEmployeeVisas() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", dod.getRandomEmployeeVisa());
        long count = org.timedesk.entity.EmployeeVisa.countEmployeeVisas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'EmployeeVisa', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.EmployeeVisa> result = org.timedesk.entity.EmployeeVisa.findAllEmployeeVisas();
        org.junit.Assert.assertNotNull("Find all method for 'EmployeeVisa' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'EmployeeVisa' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeeVisaIntegrationTest.testFindEmployeeVisaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", dod.getRandomEmployeeVisa());
        long count = org.timedesk.entity.EmployeeVisa.countEmployeeVisas();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.EmployeeVisa> result = org.timedesk.entity.EmployeeVisa.findEmployeeVisaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'EmployeeVisa' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'EmployeeVisa' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeeVisaIntegrationTest.testFlush() {
        org.timedesk.entity.EmployeeVisa obj = dod.getRandomEmployeeVisa();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeVisa.findEmployeeVisa(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeVisa' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployeeVisa(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'EmployeeVisa' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeVisaIntegrationTest.testMerge() {
        org.timedesk.entity.EmployeeVisa obj = dod.getRandomEmployeeVisa();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeVisa.findEmployeeVisa(id);
        boolean modified =  dod.modifyEmployeeVisa(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.EmployeeVisa merged = (org.timedesk.entity.EmployeeVisa) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'EmployeeVisa' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeVisaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", dod.getRandomEmployeeVisa());
        org.timedesk.entity.EmployeeVisa obj = dod.getNewTransientEmployeeVisa(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'EmployeeVisa' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'EmployeeVisa' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeeVisaIntegrationTest.testRemove() {
        org.timedesk.entity.EmployeeVisa obj = dod.getRandomEmployeeVisa();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeVisa' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeVisa.findEmployeeVisa(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'EmployeeVisa' with identifier '" + id + "'", org.timedesk.entity.EmployeeVisa.findEmployeeVisa(id));
    }
    
}
