// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.EmployeeAllocationDataOnDemand;

privileged aspect EmployeeAllocationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeeAllocationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeeAllocationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EmployeeAllocationIntegrationTest: @Transactional;
    
    @Autowired
    private EmployeeAllocationDataOnDemand EmployeeAllocationIntegrationTest.dod;
    
    @Test
    public void EmployeeAllocationIntegrationTest.testCountEmployeeAllocations() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", dod.getRandomEmployeeAllocation());
        long count = org.timedesk.entity.EmployeeAllocation.countEmployeeAllocations();
        org.junit.Assert.assertTrue("Counter for 'EmployeeAllocation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeeAllocationIntegrationTest.testFindEmployeeAllocation() {
        org.timedesk.entity.EmployeeAllocation obj = dod.getRandomEmployeeAllocation();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeAllocation.findEmployeeAllocation(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeAllocation' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'EmployeeAllocation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeeAllocationIntegrationTest.testFindAllEmployeeAllocations() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", dod.getRandomEmployeeAllocation());
        long count = org.timedesk.entity.EmployeeAllocation.countEmployeeAllocations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'EmployeeAllocation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.EmployeeAllocation> result = org.timedesk.entity.EmployeeAllocation.findAllEmployeeAllocations();
        org.junit.Assert.assertNotNull("Find all method for 'EmployeeAllocation' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'EmployeeAllocation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeeAllocationIntegrationTest.testFindEmployeeAllocationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", dod.getRandomEmployeeAllocation());
        long count = org.timedesk.entity.EmployeeAllocation.countEmployeeAllocations();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.EmployeeAllocation> result = org.timedesk.entity.EmployeeAllocation.findEmployeeAllocationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'EmployeeAllocation' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'EmployeeAllocation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeeAllocationIntegrationTest.testFlush() {
        org.timedesk.entity.EmployeeAllocation obj = dod.getRandomEmployeeAllocation();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeAllocation.findEmployeeAllocation(id);
        org.junit.Assert.assertNotNull("Find method for 'EmployeeAllocation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployeeAllocation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'EmployeeAllocation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeAllocationIntegrationTest.testMerge() {
        org.timedesk.entity.EmployeeAllocation obj = dod.getRandomEmployeeAllocation();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeAllocation.findEmployeeAllocation(id);
        boolean modified =  dod.modifyEmployeeAllocation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.EmployeeAllocation merged = (org.timedesk.entity.EmployeeAllocation) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'EmployeeAllocation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeeAllocationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", dod.getRandomEmployeeAllocation());
        org.timedesk.entity.EmployeeAllocation obj = dod.getNewTransientEmployeeAllocation(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'EmployeeAllocation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'EmployeeAllocation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeeAllocationIntegrationTest.testRemove() {
        org.timedesk.entity.EmployeeAllocation obj = dod.getRandomEmployeeAllocation();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EmployeeAllocation' failed to provide an identifier", id);
        obj = org.timedesk.entity.EmployeeAllocation.findEmployeeAllocation(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'EmployeeAllocation' with identifier '" + id + "'", org.timedesk.entity.EmployeeAllocation.findEmployeeAllocation(id));
    }
    
}
