// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.HolidayDataOnDemand;

privileged aspect HolidayIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HolidayIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HolidayIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: HolidayIntegrationTest: @Transactional;
    
    @Autowired
    private HolidayDataOnDemand HolidayIntegrationTest.dod;
    
    @Test
    public void HolidayIntegrationTest.testCountHolidays() {
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", dod.getRandomHoliday());
        long count = org.timedesk.entity.Holiday.countHolidays();
        org.junit.Assert.assertTrue("Counter for 'Holiday' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HolidayIntegrationTest.testFindHoliday() {
        org.timedesk.entity.Holiday obj = dod.getRandomHoliday();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to provide an identifier", id);
        obj = org.timedesk.entity.Holiday.findHoliday(id);
        org.junit.Assert.assertNotNull("Find method for 'Holiday' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Holiday' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HolidayIntegrationTest.testFindAllHolidays() {
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", dod.getRandomHoliday());
        long count = org.timedesk.entity.Holiday.countHolidays();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Holiday', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.Holiday> result = org.timedesk.entity.Holiday.findAllHolidays();
        org.junit.Assert.assertNotNull("Find all method for 'Holiday' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Holiday' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HolidayIntegrationTest.testFindHolidayEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", dod.getRandomHoliday());
        long count = org.timedesk.entity.Holiday.countHolidays();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.Holiday> result = org.timedesk.entity.Holiday.findHolidayEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Holiday' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Holiday' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HolidayIntegrationTest.testFlush() {
        org.timedesk.entity.Holiday obj = dod.getRandomHoliday();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to provide an identifier", id);
        obj = org.timedesk.entity.Holiday.findHoliday(id);
        org.junit.Assert.assertNotNull("Find method for 'Holiday' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHoliday(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Holiday' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HolidayIntegrationTest.testMerge() {
        org.timedesk.entity.Holiday obj = dod.getRandomHoliday();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to provide an identifier", id);
        obj = org.timedesk.entity.Holiday.findHoliday(id);
        boolean modified =  dod.modifyHoliday(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.Holiday merged = (org.timedesk.entity.Holiday) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Holiday' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HolidayIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", dod.getRandomHoliday());
        org.timedesk.entity.Holiday obj = dod.getNewTransientHoliday(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Holiday' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Holiday' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HolidayIntegrationTest.testRemove() {
        org.timedesk.entity.Holiday obj = dod.getRandomHoliday();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Holiday' failed to provide an identifier", id);
        obj = org.timedesk.entity.Holiday.findHoliday(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Holiday' with identifier '" + id + "'", org.timedesk.entity.Holiday.findHoliday(id));
    }
    
}
