// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.ProjectMemberFeedbackDataOnDemand;

privileged aspect ProjectMemberFeedbackIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjectMemberFeedbackIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjectMemberFeedbackIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProjectMemberFeedbackIntegrationTest: @Transactional;
    
    @Autowired
    private ProjectMemberFeedbackDataOnDemand ProjectMemberFeedbackIntegrationTest.dod;
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testCountProjectMemberFeedbacks() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", dod.getRandomProjectMemberFeedback());
        long count = org.timedesk.entity.ProjectMemberFeedback.countProjectMemberFeedbacks();
        org.junit.Assert.assertTrue("Counter for 'ProjectMemberFeedback' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testFindProjectMemberFeedback() {
        org.timedesk.entity.ProjectMemberFeedback obj = dod.getRandomProjectMemberFeedback();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberFeedback.findProjectMemberFeedback(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectMemberFeedback' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProjectMemberFeedback' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testFindAllProjectMemberFeedbacks() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", dod.getRandomProjectMemberFeedback());
        long count = org.timedesk.entity.ProjectMemberFeedback.countProjectMemberFeedbacks();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProjectMemberFeedback', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.ProjectMemberFeedback> result = org.timedesk.entity.ProjectMemberFeedback.findAllProjectMemberFeedbacks();
        org.junit.Assert.assertNotNull("Find all method for 'ProjectMemberFeedback' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProjectMemberFeedback' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testFindProjectMemberFeedbackEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", dod.getRandomProjectMemberFeedback());
        long count = org.timedesk.entity.ProjectMemberFeedback.countProjectMemberFeedbacks();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.ProjectMemberFeedback> result = org.timedesk.entity.ProjectMemberFeedback.findProjectMemberFeedbackEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProjectMemberFeedback' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProjectMemberFeedback' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testFlush() {
        org.timedesk.entity.ProjectMemberFeedback obj = dod.getRandomProjectMemberFeedback();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberFeedback.findProjectMemberFeedback(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectMemberFeedback' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjectMemberFeedback(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProjectMemberFeedback' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testMerge() {
        org.timedesk.entity.ProjectMemberFeedback obj = dod.getRandomProjectMemberFeedback();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberFeedback.findProjectMemberFeedback(id);
        boolean modified =  dod.modifyProjectMemberFeedback(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.ProjectMemberFeedback merged = (org.timedesk.entity.ProjectMemberFeedback) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProjectMemberFeedback' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", dod.getRandomProjectMemberFeedback());
        org.timedesk.entity.ProjectMemberFeedback obj = dod.getNewTransientProjectMemberFeedback(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProjectMemberFeedback' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProjectMemberFeedback' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjectMemberFeedbackIntegrationTest.testRemove() {
        org.timedesk.entity.ProjectMemberFeedback obj = dod.getRandomProjectMemberFeedback();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectMemberFeedback' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectMemberFeedback.findProjectMemberFeedback(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProjectMemberFeedback' with identifier '" + id + "'", org.timedesk.entity.ProjectMemberFeedback.findProjectMemberFeedback(id));
    }
    
}
