// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.timedesk.entity.ProjectMemberRole;

privileged aspect ProjectMemberRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectMemberRoleDataOnDemand: @Component;
    
    private Random ProjectMemberRoleDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ProjectMemberRole> ProjectMemberRoleDataOnDemand.data;
    
    public ProjectMemberRole ProjectMemberRoleDataOnDemand.getNewTransientProjectMemberRole(int index) {
        org.timedesk.entity.ProjectMemberRole obj = new org.timedesk.entity.ProjectMemberRole();
        obj.setName("name_" + index);
        obj.setRoleId("roleId_" + index);
        return obj;
    }
    
    public ProjectMemberRole ProjectMemberRoleDataOnDemand.getSpecificProjectMemberRole(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ProjectMemberRole obj = data.get(index);
        return ProjectMemberRole.findProjectMemberRole(obj.getId());
    }
    
    public ProjectMemberRole ProjectMemberRoleDataOnDemand.getRandomProjectMemberRole() {
        init();
        ProjectMemberRole obj = data.get(rnd.nextInt(data.size()));
        return ProjectMemberRole.findProjectMemberRole(obj.getId());
    }
    
    public boolean ProjectMemberRoleDataOnDemand.modifyProjectMemberRole(ProjectMemberRole obj) {
        return false;
    }
    
    public void ProjectMemberRoleDataOnDemand.init() {
        data = org.timedesk.entity.ProjectMemberRole.findProjectMemberRoleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ProjectMemberRole' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.ProjectMemberRole>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.ProjectMemberRole obj = getNewTransientProjectMemberRole(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
