// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.ProjectMemberDataOnDemand;
import org.timedesk.entity.ProjectPhaseDataOnDemand;
import org.timedesk.entity.ProjectPhaseMember;

privileged aspect ProjectPhaseMemberDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectPhaseMemberDataOnDemand: @Component;
    
    private Random ProjectPhaseMemberDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ProjectPhaseMember> ProjectPhaseMemberDataOnDemand.data;
    
    @Autowired
    private ProjectMemberDataOnDemand ProjectPhaseMemberDataOnDemand.projectMemberDataOnDemand;
    
    @Autowired
    private ProjectPhaseDataOnDemand ProjectPhaseMemberDataOnDemand.projectPhaseDataOnDemand;
    
    public ProjectPhaseMember ProjectPhaseMemberDataOnDemand.getNewTransientProjectPhaseMember(int index) {
        org.timedesk.entity.ProjectPhaseMember obj = new org.timedesk.entity.ProjectPhaseMember();
        obj.setAllocation(new Integer(index));
        obj.setEndDate(new java.util.Date());
        obj.setPhaseMemberId(null);
        obj.setProjectMember(projectMemberDataOnDemand.getSpecificProjectMember(index));
        obj.setProjectPhase(projectPhaseDataOnDemand.getRandomProjectPhase());
        obj.setStartDate(new java.util.Date());
        return obj;
    }
    
    public ProjectPhaseMember ProjectPhaseMemberDataOnDemand.getSpecificProjectPhaseMember(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ProjectPhaseMember obj = data.get(index);
        return ProjectPhaseMember.findProjectPhaseMember(obj.getId());
    }
    
    public ProjectPhaseMember ProjectPhaseMemberDataOnDemand.getRandomProjectPhaseMember() {
        init();
        ProjectPhaseMember obj = data.get(rnd.nextInt(data.size()));
        return ProjectPhaseMember.findProjectPhaseMember(obj.getId());
    }
    
    public boolean ProjectPhaseMemberDataOnDemand.modifyProjectPhaseMember(ProjectPhaseMember obj) {
        return false;
    }
    
    public void ProjectPhaseMemberDataOnDemand.init() {
        data = org.timedesk.entity.ProjectPhaseMember.findProjectPhaseMemberEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ProjectPhaseMember' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.ProjectPhaseMember>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.ProjectPhaseMember obj = getNewTransientProjectPhaseMember(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
