// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.timedesk.entity.ProjectMemberDataOnDemand;
import org.timedesk.entity.ProjectMemberFeedback;

privileged aspect ProjectMemberFeedbackDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectMemberFeedbackDataOnDemand: @Component;
    
    private Random ProjectMemberFeedbackDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<ProjectMemberFeedback> ProjectMemberFeedbackDataOnDemand.data;
    
    @Autowired
    private ProjectMemberDataOnDemand ProjectMemberFeedbackDataOnDemand.projectMemberDataOnDemand;
    
    public ProjectMemberFeedback ProjectMemberFeedbackDataOnDemand.getNewTransientProjectMemberFeedback(int index) {
        org.timedesk.entity.ProjectMemberFeedback obj = new org.timedesk.entity.ProjectMemberFeedback();
        obj.setDescription(null);
        obj.setProjectMember(projectMemberDataOnDemand.getRandomProjectMember());
        return obj;
    }
    
    public ProjectMemberFeedback ProjectMemberFeedbackDataOnDemand.getSpecificProjectMemberFeedback(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ProjectMemberFeedback obj = data.get(index);
        return ProjectMemberFeedback.findProjectMemberFeedback(obj.getId());
    }
    
    public ProjectMemberFeedback ProjectMemberFeedbackDataOnDemand.getRandomProjectMemberFeedback() {
        init();
        ProjectMemberFeedback obj = data.get(rnd.nextInt(data.size()));
        return ProjectMemberFeedback.findProjectMemberFeedback(obj.getId());
    }
    
    public boolean ProjectMemberFeedbackDataOnDemand.modifyProjectMemberFeedback(ProjectMemberFeedback obj) {
        return false;
    }
    
    public void ProjectMemberFeedbackDataOnDemand.init() {
        data = org.timedesk.entity.ProjectMemberFeedback.findProjectMemberFeedbackEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ProjectMemberFeedback' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.ProjectMemberFeedback>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.ProjectMemberFeedback obj = getNewTransientProjectMemberFeedback(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
