// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.timedesk.entity.ProjectPhaseMemberDataOnDemand;

privileged aspect ProjectPhaseMemberIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjectPhaseMemberIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjectPhaseMemberIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProjectPhaseMemberIntegrationTest: @Transactional;
    
    @Autowired
    private ProjectPhaseMemberDataOnDemand ProjectPhaseMemberIntegrationTest.dod;
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testCountProjectPhaseMembers() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", dod.getRandomProjectPhaseMember());
        long count = org.timedesk.entity.ProjectPhaseMember.countProjectPhaseMembers();
        org.junit.Assert.assertTrue("Counter for 'ProjectPhaseMember' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testFindProjectPhaseMember() {
        org.timedesk.entity.ProjectPhaseMember obj = dod.getRandomProjectPhaseMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhaseMember.findProjectPhaseMember(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectPhaseMember' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProjectPhaseMember' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testFindAllProjectPhaseMembers() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", dod.getRandomProjectPhaseMember());
        long count = org.timedesk.entity.ProjectPhaseMember.countProjectPhaseMembers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProjectPhaseMember', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.timedesk.entity.ProjectPhaseMember> result = org.timedesk.entity.ProjectPhaseMember.findAllProjectPhaseMembers();
        org.junit.Assert.assertNotNull("Find all method for 'ProjectPhaseMember' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProjectPhaseMember' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testFindProjectPhaseMemberEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", dod.getRandomProjectPhaseMember());
        long count = org.timedesk.entity.ProjectPhaseMember.countProjectPhaseMembers();
        if (count > 20) count = 20;
        java.util.List<org.timedesk.entity.ProjectPhaseMember> result = org.timedesk.entity.ProjectPhaseMember.findProjectPhaseMemberEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProjectPhaseMember' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProjectPhaseMember' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testFlush() {
        org.timedesk.entity.ProjectPhaseMember obj = dod.getRandomProjectPhaseMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhaseMember.findProjectPhaseMember(id);
        org.junit.Assert.assertNotNull("Find method for 'ProjectPhaseMember' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjectPhaseMember(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProjectPhaseMember' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testMerge() {
        org.timedesk.entity.ProjectPhaseMember obj = dod.getRandomProjectPhaseMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhaseMember.findProjectPhaseMember(id);
        boolean modified =  dod.modifyProjectPhaseMember(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.timedesk.entity.ProjectPhaseMember merged = (org.timedesk.entity.ProjectPhaseMember) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProjectPhaseMember' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", dod.getRandomProjectPhaseMember());
        org.timedesk.entity.ProjectPhaseMember obj = dod.getNewTransientProjectPhaseMember(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProjectPhaseMember' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProjectPhaseMember' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjectPhaseMemberIntegrationTest.testRemove() {
        org.timedesk.entity.ProjectPhaseMember obj = dod.getRandomProjectPhaseMember();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProjectPhaseMember' failed to provide an identifier", id);
        obj = org.timedesk.entity.ProjectPhaseMember.findProjectPhaseMember(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProjectPhaseMember' with identifier '" + id + "'", org.timedesk.entity.ProjectPhaseMember.findProjectPhaseMember(id));
    }
    
}
