// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.timedesk.entity;

import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.timedesk.entity.SecurityRole;

privileged aspect SecurityRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SecurityRoleDataOnDemand: @Component;
    
    private Random SecurityRoleDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<SecurityRole> SecurityRoleDataOnDemand.data;
    
    public SecurityRole SecurityRoleDataOnDemand.getNewTransientSecurityRole(int index) {
        org.timedesk.entity.SecurityRole obj = new org.timedesk.entity.SecurityRole();
        obj.setName("name_" + index);
        obj.setSecurityRoleId("securityRoleId_" + index);
        return obj;
    }
    
    public SecurityRole SecurityRoleDataOnDemand.getSpecificSecurityRole(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        SecurityRole obj = data.get(index);
        return SecurityRole.findSecurityRole(obj.getId());
    }
    
    public SecurityRole SecurityRoleDataOnDemand.getRandomSecurityRole() {
        init();
        SecurityRole obj = data.get(rnd.nextInt(data.size()));
        return SecurityRole.findSecurityRole(obj.getId());
    }
    
    public boolean SecurityRoleDataOnDemand.modifySecurityRole(SecurityRole obj) {
        return false;
    }
    
    public void SecurityRoleDataOnDemand.init() {
        data = org.timedesk.entity.SecurityRole.findSecurityRoleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'SecurityRole' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.timedesk.entity.SecurityRole>();
        for (int i = 0; i < 10; i++) {
            org.timedesk.entity.SecurityRole obj = getNewTransientSecurityRole(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
